<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header('Location: /acc_security/login.php');
    exit();
}
require_once 'db.php';

$user_id = $_SESSION['user_id'];
$product_id = $_POST['product_id'] ?? null;
$action = $_POST['wishlist_action'] ?? '';

if ($product_id && in_array($action, ['add', 'remove'])) {
    if ($action === 'add') {
        // Check if already in wishlist
        $stmt = $conn->prepare('SELECT * FROM wishlist WHERE User_ID = ? AND Product_ID = ?');
        $stmt->execute([$user_id, $product_id]);
        if (!$stmt->fetch()) {
            // Wishlist_ID will be generated by trigger
            $stmt = $conn->prepare('INSERT INTO wishlist (Product_ID, User_ID) VALUES (?, ?)');
            $stmt->execute([$product_id, $user_id]);
        }
    } elseif ($action === 'remove') {
        $stmt = $conn->prepare('DELETE FROM wishlist WHERE User_ID = ? AND Product_ID = ?');
        $stmt->execute([$user_id, $product_id]);
    }
}

if ($action === 'add') {
    header('Location: products.php');
} else {
    // Get the referring page
    $referer = $_SERVER['HTTP_REFERER'] ?? 'products.php';
    header('Location: ' . $referer);
}
exit(); 